cargo-features = ["edition"]

[package]
name = "squid-inline"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/squid-lang/squid"

[dependencies]
squid-core = { path = "../squid-core" }